### ISSUE TITLE
Commas are incorrectly matched as escape characters in Clojure files

### ISSUE THREAD

**Issue by ChrisBlom** [zk-phi/highlight-stages#2]
highligh-stages incorrectly highlights the following snippet:

```clojure
{:a 1, :b 2}
```
It highlights ':b 2', but in Clojure comma's are treated as whitespace and not an escape symbols, 
Clojure uses '~' for escaping instead

**Comment by zk-phi** [comment]
Thanks, I'll implement Clojure support.

**Comment by ChrisBlom** [comment]
Thanks, it turned out to be a simple fix, i've sent you a PR
